export { defineConfig, defineScreen } from "./defineScreen.js"
export { extractNavigationTargets } from "./extractNavigationTargets.js"
export {
	type AdoptionConfig,
	type ApiIntegrationConfig,
	adoptionSchema,
	apiIntegrationSchema,
	type Config,
	type ConfigInput,
	configSchema,
	// Mock types
	type MockButtonElement,
	type MockElement,
	type MockElementType,
	type MockImageElement,
	type MockInputElement,
	type MockLayout,
	type MockLinkElement,
	type MockListElement,
	type MockSection,
	type MockTableElement,
	type MockTextElement,
	type Screen,
	type ScreenInput,
	type ScreenLink,
	type ScreenLinkType,
	type ScreenMock,
	screenMockSchema,
	screenSchema,
} from "./types.js"
